# Generated by Django 5.2.6 on 2025-09-13 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Running', 'Running Shoes'), ('Indoor', 'Indoor Shoes'), ('Football', 'Football Shoes'), ('Match Ball', 'Football')], default='Running', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
