# Generated by Django 5.2.6 on 2025-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Running', 'Running Shoe'), ('Indoor', 'Indoor Shoe'), ('Football', 'Football Shoe'), ('Ball', 'Football')], default='Running', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
