# Generated by Django 5.2.6 on 2025-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Running', 'Running Shoes'), ('Indoor', 'Indoor Shoes'), ('Football', 'Football Shoes'), ('MatchBall', 'Match Ball'), ('Misc', 'Miscellaneous')], max_length=10),
        ),
    ]
