# Generated by Django 5.2.6 on 2025-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Running', 'Running Shoes'), ('Indoor', 'Indoor Shoes'), ('Football', 'Football Shoes'), ('Match Ball', 'Football')], default='Running', max_length=10),
        ),
    ]
