# Generated by Django 5.2.6 on 2025-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Running', 'Running Shoes'), ('Indoor', 'Indoor Shoes'), ('Football', 'Football Shoes'), ('Match Ball', 'Match Ball'), ('Misc', 'Miscellaneous')], max_length=10),
        ),
    ]
