# Generated by Django 5.2.6 on 2025-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_id_product_idproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='idproduct',
            new_name='id',
        ),
    ]
